#!/bin/bash

# Set it up to use the locally installed Perl 5.14.1
export PATH="/home/recollect/perl5/perlbrew/perls/perl-5.14.1/bin:$PATH"
PERL_CPANM_OPT="--local-lib=/home/recollect/perl5"
source /home/recollect/perl5/perlbrew/etc/bashrc

OIL=/var/www/oilert
export PERL5LIB="$OIL/lib"

exec 2>&1 \
    /home/recollect/perl5/perlbrew/perls/perl-5.14.1/bin/starman --listen 127.0.0.1:6000 --workers 2 --preload-app \
        --user recollect --group www-data \
        $OIL/app.psgi >> /var/log/oil-web.log 2>&1
